version: '3.8'
services:
  bot:
    container_name: bot
    build:
      context: ./bot/
      dockerfile: Dockerfile.bot
    environment:
      - EXPRESS_SERVER=api:3000
    depends_on:
      - api
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.0.0.2
  api:
    container_name: api
    build: 
      context: ./api/
      dockerfile: Dockerfile.api
    environment:
      - POSTGRES_USER=user
      - POSTGRES_HOST=10.0.0.4
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=api
    ports:
      - '0.0.0.0:3000:3000'
    depends_on:
      - pg
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.0.0.3
  pg:
    container_name: pg
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api
    ports:
      - 5432:5432
    networks:
      vpcbr:
        ipv4_address: 10.0.0.4
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1