name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  unit-test-api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies for API
        run: yarn install
        working-directory: ./api
      - name: Unit Test Bot
        run: yarn test
        working-directory: ./api
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DATABASE: test
      - name: Install Dependencies for Bot
        run: yarn install
        working-directory: ./bot
      - name: Unit Test Bot
        run: yarn test
        working-directory: ./bot